**Task : logistic regression model that predicts whether a person buys computer or not.**

In [ ]:
#import libraries
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt

In [ ]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
data=pd.read_csv('BuyComputer.csv')
print(data)
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

      User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
#Declare label as last column in the source file
y = data.iloc[: , -1].values
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [ ]:
#Declaring X as all columns excluding last
import pandas as pd
data=pd.read_csv('BuyComputer.csv')
x = data.iloc[:,:-1].values
print(x)

[[15624510       19    19000]
 [15810944       35    20000]
 [15668575       26    43000]
 ...
 [15654296       50    20000]
 [15755018       36    33000]
 [15594041       49    36000]]


In [ ]:
# Splitting data
import pandas as pd
data=pd.read_csv('BuyComputer.csv')
y = data.iloc[: , -1].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data,y,random_state=98)

In [ ]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(x_train[0])
w = []
b = 0.2
print(len_x)

4


In [ ]:
entries = len(x_train[:,0])
entries

300

In [ ]:
for weights in range(len_x):
  w.append(0)
w

[0, 0, 0, 0]

In [ ]:
# Sigmoid function
import numpy as np
def sigmoid(z):
  return 1.0/(1 + np.exp(-np.dot(z, b)))


def predict(inputs):
  pred_prob = sigmoid(inputs)
  pred_value = np.where(pred_prob >= .5, 1, 0)
  return np.squeeze(pred_value)

In [ ]:
#Loss function
def loss_func(y,a):
  log_func_v = sigmoid(y)
  print(log_func_v)
  a = np.squeeze(a)
  step1 = a * np.log(log_func_v)
  step2 = (1 - a) * np.log(1 - log_func_v)
  final = -step1 - step2
  return np.mean(final)

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)

In [ ]:
for i in range(3000):
  y_pred = predict(x_train[0])
  print(y_pred)

In [ ]:
l_pred = predict(y)
for i in range(len(y)):
  print("predicted: " + str(l_pred[i]) + " actual: " + str(y[i]))

In [ ]:
from sklearn import metrics

print(metrics.classification_report(y, l_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       257
           1       0.36      1.00      0.53       143

    accuracy                           0.36       400
   macro avg       0.18      0.50      0.26       400
weighted avg       0.13      0.36      0.19       400



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 98)
LR.fit(x_train,y_train)

LogisticRegression(random_state=98)

In [ ]:
prediction = LR.predict(x_test)
print(prediction)

[1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1
 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0
 0 1 1 0 1 0 0 1 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 0 0 1]


In [ ]:
from sklearn import metrics

print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        58
           1       1.00      1.00      1.00        42

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [ ]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf
import numpy as np

In [ ]:
from tensorflow.keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
mnist.y_onehot = True
print('Train: x:{}, y:{}'.format(len(x_train),y_train.shape))

Train: x:60000, y:(60000,)


In [ ]:
# setting up hyper parameter & MNIST data parameter
learning_rate = 0.01
training_steps = 1000
batch_size = 256
display_step = 50
n_epochs = 5
num_classes = 10 # 0 to 9 digits
num_features = 784 # 28*28

In [ ]:
x = tf.placeholder(dtype=tf.float32, shape=[None, mnist.n_features])
y = tf.placeholder(dtype=tf.float32, shape=[None, mnist.n_classes])
w = tf.Variable(tf.zeros([mnist.n_features, mnist.n_classes]))
b = tf.Variable(tf.zeros([mnist.n_classes]))

In [ ]:
# LOGISTIC REGRESSION MODEL
actv = tf.nn.softmax(tf.matmul(x, w) + b)

# Clip prediction values to avoid log(0) error.
epsilon = tf.keras.backend.epsilon()
y_hat = tf.nn.softmax(actv)
y_hat_clipped = tf.clip_by_value(y_hat, epsilon, 1 - epsilon)
y_hat_log = tf.log(y_hat_clipped)

# Compute cross-entropy.
cross_entropy = -tf.reduce_sum(y * y_hat_log, axis=1)

# COST FUNCTION
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(actv), reduction_indices=1))

# OPTIMIZER
loss_f = tf.reduce_mean(cross_entropy)
optimizer = tf.train.GradientDescentOptimizer
optimizer_f = optimizer(learning_rate=learning_rate).minimize(loss_f)

# PREDICTION
pred = tf.equal(tf.argmax(actv, 1), tf.argmax(y, 1)) 

# ACCURACY
accr = tf.reduce_mean(tf.cast(pred, "float"))

In [ ]:
n_batches = int(60000/mnist.batch_size)
tf.global_variables_initializer().run()
sess = tf.Session()
for epoch in range(n_epochs):
  mnist.reset_index()
  for batch in range(n_batches):
    x_batch, y_batch = mnist.next_batch()
    feed_dict={x: x_batch, y: y_batch}
    accuracy_score = sess.run(accr, feed_dict=feed_dict)